[theme]
primaryColor = "#FF2E63"
backgroundColor = "#0A0A0F"
secondaryBackgroundColor = "#161622"
textColor = "#FFFFFF"
font = "inter"

[server]
enableCORS = false
headless = true

[runner]
magicEnabled = false

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false
